# Generated by Django 4.1.3 on 2023-04-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='depart',
            new_name='depart_id',
        ),
    ]
