# Generated by Django 4.2 on 2023-04-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_depart_userinfo_depart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='depart_id',
            new_name='depart',
        ),
    ]
